# Generated by Django 6.0.7 on 2026-07-20 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kullanici',
            name='yillik_izin_hakki',
            field=models.IntegerField(default=14),
        ),
    ]
